In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import math

import FROG as frog

In [7]:
#file = pd.read_csv('data_1400_afterBS.dat', header = None, delimiter =',')    #Take the file given from the FROG setup and import it here


#Coded here

def load_files(filename = 'data_1400_afterBS.dat', wave = 'wavelengths_1400_afterBS.dat', time = 'times_1400_afterBS.dat'):
    spec = pd.read_csv(filename, header = None, delimiter =',')

    lam = pd.read_csv(wave, header = None, delimiter =',')

    time = pd.read_csv(time, header = None, delimiter =',')

    return spec, lam, time


data_file = load_files()[0] #Units of unknown, it's an intensity though. 
wave_file = load_files()[1] #Units of nm
time_file = load_files()[2] #Units of s?

#Loads in files

In [14]:
#Putting my code into a package, FROG.py, so I will call it and make sure it works:

data_file = frog.load_files()[0]
wave_file = frog.load_files()[1]
time_file = frog.load_files()[2]

#Loads in files

data_file #Data (Intensities)

,0,1,2,3,4,5,6,7,8,9,...,123,124,125,126,127,128,129,130,131,132
0,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,...,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755,-2284.096755
1,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,...,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480,24939.986480
2,-4.253016,-18.452342,7.106445,23.009689,-29.811802,-0.845178,-4.253016,-3.117070,-22.428153,30.961312,...,-16.180450,-1.413151,-25.268018,-10.500719,-12.772611,-17.316396,0.858741,-46.850993,-1.981124,-4.253016
3,-75.249645,-40.603290,-41.739236,-36.059506,-73.545726,-40.603290,-78.089510,-50.826804,-46.850993,-37.763425,...,-46.850993,-86.609105,-67.298022,-61.050319,-32.651667,-45.715047,-66.162076,-61.050319,-66.162076,-24.700045
4,-53.666670,-42.875182,-61.618292,-48.554912,-40.035317,-72.409780,-37.195452,-34.923560,-34.923560,-56.506535,...,-71.841806,-61.050319,-66.730049,-44.579101,-41.739236,-49.122885,-14.476531,-47.418966,-60.482346,-60.482346
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2043,420.590810,420.590810,417.182972,414.911080,439.333920,433.654189,433.654189,395.599997,427.406486,357.545804,...,412.639187,395.599997,410.935268,435.926082,409.231349,413.207160,435.358109,383.672563,395.032024,407.527430
2044,406.391484,430.246351,413.775133,406.391484,418.318918,388.784320,384.240536,417.182972,417.182972,419.454864,...,370.609183,406.391484,405.823511,434.222163,367.769318,382.536617,402.415673,409.799322,422.862702,425.702567
2045,426.270540,427.974459,407.527430,417.750945,427.974459,422.294729,392.760131,399.575808,413.207160,441.605812,...,358.681750,402.415673,420.022837,405.823511,388.784320,383.672563,389.920266,417.750945,401.847700,387.080401
2046,426.270540,427.974459,407.527430,417.750945,427.974459,422.294729,392.760131,399.575808,413.207160,441.605812,...,358.681750,402.415673,420.022837,405.823511,388.784320,383.672563,389.920266,417.750945,401.847700,387.080401
2047,426.270540,427.974459,407.527430,417.750945,427.974459,422.294729,392.760131,399.575808,413.207160,441.605812,...,358.681750,402.415673,420.022837,405.823511,388.784320,383.672563,389.920266,417.750945,401.847700,387.080401

In [13]:
wave_file #Wavelengths

                0
0      339.625370
1      340.007542
2      340.389668
3      340.771747
4      341.153779
...           ...
2043  1014.402855
2044  1014.676953
2045  1014.950992
2046  1015.224971
2047  1015.498891

[2048 rows x 1 columns]

In [12]:
time_file #Times

              0
0      0.000000
1      2.015152
2      4.030303
3      6.045455
4      8.060606
..          ...
128  257.939394
129  259.954545
130  261.969697
131  263.984848
132  266.000000

[133 rows x 1 columns]

In [15]:
#Imports are all worked out, now need to double check everything looks good:

#frog.heat_map(data_file, x = wave_file, y = data_file, nbinsx = 15, nbinsy = 20, color_continuous_scale = 'Greens', title_text = 'Intensity vs. Wavelength (nm)')

#Heat map will plot out the spectrometer data we imported above.

In [6]:
frog.Analysis() #Analysis function, need to make sure the intial importation is correct units wise before I can dive right into analysis.

This function will output the analysis of the FROG data